version: '3.7'
services:
  postgres:
    image: postgres
    networks:
      - postgres
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - postgres
    restart: always
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0
    networks:
      - postgres
    restart: always
networks:
  postgres:
    driver: bridge
